default_language_version:
  python: python2.7

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: no-commit-to-branch
        args: [--branch, master]
    -   id: check-added-large-files
    -   id: check-ast
    -   id: debug-statements
    -   id: check-builtin-literals
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-vcs-permalinks
    -   id: check-json
    -   id: check-yaml
    -   id: check-xml
    -   id: detect-private-key
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
        args: ['--fix=no']
    -   id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
    -   id: end-of-file-fixer
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
    -   id: forbid-crlf
    -   id: forbid-tabs
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.17.1
    hooks:
      - id: pyupgrade
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.0
    hooks:
    -   id: seed-isort-config
        stages: [manual]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
    -   id: isort
        additional_dependencies: ['isort[pyproject]']
-   repo: https://github.com/python/black
    rev: a4399f3054206eac52a89832a415e31077bafa0a
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8
-   repo: git://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.0
    hooks:
    -   id: python-safety-dependencies-check
        stages: [manual]
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.4
    hooks:
    -   id: python-bandit-vulnerability-check
        stages: [manual]
